### ISSUE TITLE
smoke test is failing

### ISSUE THREAD

**Issue by mohit84** [gluster/project-infrastructure#105]
The smoke test is failing on this pull request  https://github.com/gluster/glusterfs/pull/1776
https://build.gluster.org/job/gh_devrpm-el6/394/console

**Comment by deepshikhaaa** [comment]
@mohit84 It is failing for your patch only. I ran it for the devel branch https://build.gluster.org/job/gh_devrpm-el7/402/ and it passed.

It is not an infra issue. Could you please check the code in your PR which is failing the rpm build jobs?

**Comment by mscherer** [comment]
@deepshikhaaa seems you ran EL7, not EL6. But yes, EL6 seems fine on another node:
https://build.gluster.org/job/gh_devrpm-el6/395/console

However, I can't understand the error, seems to not be displayed. Could have been a fluke ?

Shall I close that one ?

**Comment by mohit84** [comment]
Yes you can close the bug.The issue was in my patch.

**Comment by deepshikhaaa** [comment]
@mscherer It was failing for all the devrpm jobs. So I just ran one of them. 

Closing this issue.
