### ISSUE TITLE
Update Community meeting link in Gluster-devel email signature

### ISSUE THREAD

**Issue by msaju** [gluster/project-infrastructure#106]
Please update the Gluster-devel email signature to below. We missed to update Gluster-devel when we did the same for Gluster-users mailing list.(https://github.com/gluster/project-infrastructure/issues/99)

Community Meeting Calendar:
Schedule -
Every 2nd and 4th Tuesday at 14:30 IST / 09:00 UTC
Bridge: https://meet.google.com/cpu-eiue-hvk
Gluster-devel mailing list
Gluster-devel@gluster.org
https://lists.gluster.org/mailman/listinfo/gluster-devel

**Comment by mscherer** [comment]
Ok, done
