### ISSUE TITLE
smoke test is failing

### ISSUE THREAD

**Issue by mohit84** [gluster/project-infrastructure#107]
A smoke test is failing
https://build.gluster.org/job/gh_devrpm-el6/524/

**Comment by deepshikhaaa** [comment]
The mock build for el6 is failing because http://mirror.centos.org/centos/6/ is deprecated and will not support this version.

``` 
https://wiki.centos.org/FAQ/General

Please keep in mind that 6.0, 6.1, 6.2, 6.3, 6.4 , 6.5, 6.6, 6.7, 6.8 , 6.9 and 6.10 no longer get any updates, nor
any security fix's.
The whole CentOS 6 is *dead* and *shouldn't* be used anywhere at *all* 
```
The mock build uses this mirror for epel6.

**Comment by mohit84** [comment]
I think we need to change the script otherwise we can not merge the changes,
Currently devrpm-el6 is mandatory to merge a patch.

**Comment by deepshikhaaa** [comment]
I had a conversation with Niels about the support for el6. We can drop the el6 testing as the Centos6 is EOL. I will make the appropriate changes to disable the el6 job.

**Comment by deepshikhaaa** [comment]
Disabled the job gh_devrpm-el6 https://build.gluster.org/view/Github%20jobs/job/gh_devrpm-el6/ and removed from the branch protection rule.
