### ISSUE TITLE
[bug:1805011] smoke Build fails with no such file or directory

### ISSUE THREAD

**Issue by gluster-ant** [gluster/project-infrastructure#11]
URL: https://bugzilla.redhat.com/1805011
Creator: hgowtham at redhat
Time: 20200220T05:43:20

Description of problem:
The build fails for https://review.gluster.org/#/c/build-jobs/+/23172/
With the error:

12:10:06 [build-job] $ /bin/sh /tmp/jenkins360143079291067817.sh
12:10:06 /tmp/jenkins360143079291067817.sh: line 3: /opt/rh/python27/enable: No such file or directory
12:10:06 Build step 'Execute shell' marked build as failure
12:10:06 Finished: FAILURE

https://build.gluster.org/job/build-job/575/console

Actual results:
Failure

Expected results:
Pass/ the smoke to start running fine.

Additional info:

**Comment by gluster-ant** [comment]
Time: 20200220T11:39:34
dkhandel at redhat commented: 
This job has been running on Centos8 builders now.

Michael, would it be a good to have a python3 env for tox?

I tested it in python3 virtual env, it is working fine there.

**Comment by gluster-ant** [comment]
Time: 20200220T14:41:47
mscherer at redhat commented: 
yeah, it seems like a good idea.

**Comment by gluster-ant** [comment]
Time: 20200228T11:45:57
hgowtham at redhat commented: 
I started to see similar failure for https://review.gluster.org/#/c/build-jobs/+/23289/ patch as well

**Comment by gluster-ant** [comment]
Time: 20200228T12:02:24
dkhandel at redhat commented: 
I was testing earlier and now the script in the configuration is upated to the previous state. I will fix it in the build-jobs repo.

**Comment by mscherer** [comment]
Given build job was moved to python 3, I think we can safely close this bug
