### ISSUE TITLE
Do we need comment-on-issue jenkins job after migration to Github?

### ISSUE THREAD

**Issue by deepshikhaaa** [gluster/project-infrastructure#116]
https://build.gluster.org/job/gh_comment-on-issue/

**Comment by mscherer** [comment]
Fixed in https://github.com/gluster/build-jobs/commit/3e4a1e902f74cdf57cdf5e5d6a98cee56ed9634a

**Comment by mscherer** [comment]
ok so it was removed on 2f0d370f2c2a309f3c6c0b6fc1e1bc41f7df55ef rather than the commit I gave. I will remove from jenkins
