### ISSUE TITLE
Blog posts updation in planet.gluster.org

### ISSUE THREAD

**Issue by schaffung** [gluster/project-infrastructure#118]
The latest blog posts are not being updated in planet.gluster.org. On noticing the last updated blog post, it is dated to Dec '20.

**Comment by mscherer** [comment]
Indeed: https://build.gluster.org/job/planet/

**Comment by mscherer** [comment]
Seems to be broken since Fedora 30 is EOL.

**Comment by mscherer** [comment]
ok so that one is going to be interesting to fix. We need to install a new Fedora and/or a Centos 8 system to run a new Fedora mock. Or I move everything to Openshift, but that's a lot more work.

**Comment by schaffung** [comment]
Oh! I thought it might be just a small configuration issue with the change of year..

**Comment by deepshikhaaa** [comment]
@mscherer Can't we run it on Fedora32 or Fedora33?

**Comment by mscherer** [comment]
We could. I am not sure if that need to be on a VM in the cage or not. I was under the impression it would need to be on the cage, but maybe not.

**Comment by amarts** [comment]
Can it run as a GitHub action instead?

**Comment by mscherer** [comment]
No, we have to upload the files on the webserver, who sit in the lan.

**Comment by mscherer** [comment]
Ok so the build fail on F32.

**Comment by mscherer** [comment]
Another reason it can't run as a github action is that we can't run github action with cron to download new articles (as far as I know).

**Comment by mscherer** [comment]
And now, the playbook to install builders is broken. I should have stayed in bed :)

**Comment by mscherer** [comment]
Ok so now, we have a working F32 host, and it fail again on F32:
https://build.gluster.org/job/planet/393/console

**Comment by mscherer** [comment]
I am trying this PR to fix the problem: https://github.com/gluster/planet-gluster/pull/74

**Comment by mscherer** [comment]
Ok so next try: https://github.com/gluster/planet-gluster/pull/75

**Comment by mscherer** [comment]
As planet is running fine (from what I see, I am closing that bug.
