### ISSUE TITLE
gh-devrpm-fedora builds are failing

### ISSUE THREAD

**Issue by msaju** [gluster/project-infrastructure#121]
rpm fedora builds upstream is failing due to the below reason.

20:05:05 Error Summary
20:05:05 -------------
20:05:05 Disk Requirements:
20:05:05    At least 343MB more space needed on the / filesystem.

**Comment by deepshikhaaa** [comment]
It is an issue with builder49 which ran out of space. I did disconnect the builder from jenkins instance.

**Comment by mscherer** [comment]
Mhh, builder49 just got reinstalled for planet, I guess something went wrong.

**Comment by mscherer** [comment]
Log, for the record: https://build.gluster.org/job/gh_devrpm-fedora/1178/

**Comment by mscherer** [comment]
I removed it from the fedora32 group, so the rpm jobs should no longer go there, only planet and bugs summary (bugs summary being soon deprecated).

**Comment by deepshikhaaa** [comment]
builder49 is still disconnected. should I connect back? @mscherer

**Comment by itisravi** [comment]
https://build.gluster.org/job/gh_devrpm-fedora/1186/console failed on  builder-f32-2.int.aws.gluster.org, so I think the issue is still there.

**Comment by deepshikhaaa** [comment]
It is a different issue. Yesterday, I fixed it by manually deleting the leftovers of previous runs. But we need to handle this issue from the script. I am looking into it.

**Comment by msaju** [comment]
Looks like some missing scripts...
https://ci.centos.org/view/Gluster/job/gluster_build-rpms/15094/console

**Comment by deepshikhaaa** [comment]
Sent the fix for the same. Closing it now.
