### ISSUE TITLE
Need merging rights for master branch on repostory glusterfs-containers-tests

### ISSUE THREAD

**Issue by vamahaja** [gluster/project-infrastructure#123]
Provide merging rights for github ids `vamahaja` and `aloganat`

**Comment by mscherer** [comment]
So, vamahaja and aloganat account would need 2FA enabled (RH infosec requirements, see GitHub Security Guidelines ). We are still rolling that out across projects, so we haven't mandated that yet project wide, but that should happen soon.

**Comment by deepshikhaaa** [comment]
FYI, vamahaja is already an admin for this repo!

**Comment by deepshikhaaa** [comment]
Sent an invite to `aloganat` for gluster org membership and given her the write permissions for this repo.
