### ISSUE TITLE
Not able to run full-regression job 

### ISSUE THREAD

**Issue by mohit84** [gluster/project-infrastructure#126]
run full-regression job is failing due to io-uring is not available on server
https://build.gluster.org/job/gh_regression-on-demand-full-run/47/console

**Comment by deepshikhaaa** [comment]
https://github.com/gluster/glusterfs-patch-acceptance-tests/commit/adecbcfb7b63329f1877865cdcaa81108bf9b235 should fix the issue.

Lets wait for the script to get updated on builders.

**Comment by deepshikhaaa** [comment]
https://build.gluster.org/view/Github%20jobs/job/gh_regression-on-demand-full-run/48/console -test run

It is running fine now.
