### ISSUE TITLE
Can we move 'shellcheck' to nightly (or weekly) and remove from smoke?

### ISSUE THREAD

**Issue by amarts** [gluster/project-infrastructure#127]
That way, when we look at every PR, we see a clear :heavy_check_mark: instead of :x:, which is very critical for both reviewers and patch submitters to visually prioritize their reviews.

What do you think @xhernandez @pranithk @mohit84 ?

**Comment by deepshikhaaa** [comment]
https://github.com/gluster/build-jobs/pull/82 PR to make the job run nightly.

**Comment by mscherer** [comment]
Since shellcheck moved to nightly, I am closing that bug
