### ISSUE TITLE
Need admin access for build.gluster.org

### ISSUE THREAD

**Issue by msaju** [gluster/project-infrastructure#130]
Please grant admin access for add/modify/edit jobs in build.gluster.org

**Comment by mscherer** [comment]
We use a git repository for that, any change must be in git: https://github.com/gluster/build-jobs/

Can you explain the context a bit more, what do you want to modify, etc, etc ?

**Comment by msaju** [comment]
Basically it is to do some small cleanup/changes in Jenkins as and when it comes.
Its confusing while looking into dashboard.

Few eg are as below:

1. Change dashboard view to show only active jobs (big list of active/inactive jobs)
2. Rename jobs ( eg: centos8-regression should be under gh_)
3. Disable builds shown as active and not triggered / used ( few of them are not run for more than 6 months)

**Comment by deepshikhaaa** [comment]
@msaju If you want to make any changes on Jenkins like renaming and disabling the inactive jobs, etc, https://github.com/gluster/build-jobs/ is the repo that needs to update. We do everything via JJB.

**Comment by mscherer** [comment]
So closing that one, since the change need to be done by JJB.
