### ISSUE TITLE
Request for merge permissions for glusterfs release 8 release 9 and glusterdocs

### ISSUE THREAD

**Issue by Shwetha-Acharya** [gluster/project-infrastructure#131]
Please enable me (kerberose: sacharya) with merge permissions for release 8, release 9 branches of [glusterfs](https://github.com/gluster/glusterfs) and the [glusterdocs](https://github.com/gluster/glusterdocs) inorder to participate in upstream release activities.

**Comment by deepshikhaaa** [comment]
Added you in the `gluster-project-management` team on github.

**Comment by Shwetha-Acharya** [comment]
closing this issue as permission is granted
