### ISSUE TITLE
Permission for "Build with parameters" in jenkins

### ISSUE THREAD

**Issue by Shwetha-Acharya** [gluster/project-infrastructure#133]
When logged in using github to https://build.gluster.org/job/release-new, I am not able to access "Build with parameters" option.

Please add the required permissions.

**Comment by deepshikhaaa** [comment]
can you please check now?

**Comment by Shwetha-Acharya** [comment]
Thanks for the resolution @deepshikhaaa 
Closing the issue as I am now able to access "Build with parameters" option
