### ISSUE TITLE
add the link to the release notes for version 9 at https://www.gluster.org/release-schedule/

### ISSUE THREAD

**Issue by Shwetha-Acharya** [gluster/project-infrastructure#134]
The link for release notes for version 9 does not exist: https://www.gluster.org/release-schedule/
@mscherer @deepshikhaaa

**Comment by mscherer** [comment]
Indeed. Not sure who did it in the past, but I will fix it.

**Comment by mscherer** [comment]
Done:
https://www.gluster.org/release-schedule/

However, i would need the others informations, or I can give access to whoever is responsible for that part of the release

**Comment by Shwetha-Acharya** [comment]
> Done:
> https://www.gluster.org/release-schedule/
> 
> However, i would need the others informations, or I can give access to whoever is responsible for that part of the release

I am not sure if I understand about the others informations, but  I can take up this part of updating it in future, as I will be handling upstream releases.

**Comment by mscherer** [comment]
There is no EOL date. I am not sure either hat is the difference between "maintained" and "current". And what is "maintenance day" exactly ?

**Comment by Shwetha-Acharya** [comment]
Basically we will be supporting two releases at any time
1. the latest release (release 9 in this case)
2. the previous release (release 8 in this case)

Once release 10 is up, release 8 will be "EOL" and release 9 will go to "maintained".
release 10 will be "current".

**Comment by mscherer** [comment]
I think the meaning should be explained on the page. I created a account, you should have received the info on your redhat email. 

The page to edit the release page is https://www.gluster.org/wp-admin/post.php?post=8780&action=edit 

If you have any questions on wordpress, feel free to contact me.

**Comment by Shwetha-Acharya** [comment]
Thanks for creating teh account!
I have made the required changes in https://www.gluster.org/release-schedule/

**Comment by mscherer** [comment]
So, i think this ticket can be closed ?

**Comment by Shwetha-Acharya** [comment]
Closing the issue as the problem is been resolved
