### ISSUE TITLE
Softserve:Node not coming up in dasboard after machine create

### ISSUE THREAD

**Issue by Shwetha-Acharya** [gluster/project-infrastructure#135]
Machines never come up after the create command in https://softserve.gluster.org/dashboard @deepshikhaaa

**Comment by mscherer** [comment]
I also seems to have a issue, the log in my case say this is linked to ssh keys:
```
juil. 12 08:16:53 softserve.int.rht.gluster.org celery[7602]: [2021-07-12 08:16:53,560: ERROR/ForkPoolWorker-1] Task softserve.lib.create_node[71a878ca-5167-49f5-859f-737b17493ee4] raised unexpected: EC2ResponseError: 400 Bad Request
```

**Comment by deepshikhaaa** [comment]
It's now working. Not sure what went wrong there earlier. The last error I saw in logs was with SQLAlchemy populated with some unwanted data. I rolled it back and it's now working.
