### ISSUE TITLE
smoke failures on: https://github.com/gluster/glusterfs/pull/2718https://github.com/gluster/glusterfs/pull/2718

### ISSUE THREAD

**Issue by Shwetha-Acharya** [gluster/project-infrastructure#139]
32 bit build smoke:

17:28:13 ERROR: Command failed: 
17:28:13  # /usr/bin/systemd-nspawn -q -M e5ba54856f7342e3a90034cc2d896d67 -D /var/lib/mock/fedora-33-i686-bootstrap/root -a --capability=cap_ipc_lock --bind=/tmp/mock-resolv.rbozhy5z:/etc/resolv.conf --console=pipe --setenv=TERM=vt100 --setenv=SHELL=/bin/bash --setenv=HOME=/var/lib/mock/fedora-33-i686/root/installation-homedir --setenv=HOSTNAME=mock --setenv=PATH=/usr/bin:/bin:/usr/sbin:/sbin --setenv=PROMPT_COMMAND=printf "\033]0;<mock-chroot>\007" --setenv=PS1=<mock-chroot> \s-\v\$  --setenv=LANG=C.UTF-8 --setenv=LC_MESSAGES=C.UTF-8 --resolv-conf=off /usr/bin/dnf --installroot /var/lib/mock/fedora-33-i686/root/ --releasever 33 --setopt=deltarpm=False --allowerasing --disableplugin=local --disableplugin=spacewalk install langpacks-en glibc-langpack-en automake autoconf libtool flex bison openssl-devel libxml2-devel python-devel libaio-devel libibverbs-devel librdmacm-devel readline-devel lvm2-devel glib2-devel userspace-rcu-devel libcmocka-devel libacl-devel sqlite-devel fuse-devel redhat-rpm-config clang clang-analyzer git rpcgen libtirpc-devel libuuid-devel rpcgen liburing-devel --setopt=tsflags=nocontexts
17:28:13 

devrpm-el7:

cleanup chroot fails with:
OSError: [Errno 16] Device or resource busy: '/var/lib/mock/epel-7-x86_64/root/proc/filesystems'

**Comment by rakshithakamath94** [comment]
The issue is resolved.

**Comment by rakshithakamath94** [comment]
The issue is resolved.
