### ISSUE TITLE
[bug:1711950] Account in download.gluster.org to upload the build packages

### ISSUE THREAD

**Issue by gluster-ant** [gluster/project-infrastructure#14]
URL: https://bugzilla.redhat.com/1711950
Creator: sacharya at redhat
Time: 20190520T13:25:51

Description of problem: 
Need an account in download.gluster.org to upload upload the build packages.

rsa-public key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDXjiqCChrq8B/cJaRx9W3YQdtEo60dGwxuILdtw4xvQQz2/NwPKNAeOZ/1McfLv8zzuJa2Jm8mBzVk3Cc1NO0lRy3hUUphSHGrGe7BjL2WysXk4pYNYrNIza1X6EXjEDphvfRw7FU3DKVMIisOPnOgWW0xGT8Wb5XVfIfQzpW3ZJJX/aR2Nsjas2Dwxbf9hMfPHRNz5OQmNtpbqmkrcr/PC+9t7B5JJ+kdTe8x920/+7EaCTuAIOsin8fPxK4XoynA6BBuZu7B0rZbOm4DfL59loE2304epXbhvJkaTrNnkZOoQJRn4ruLDGq4F5jzCrOZyOH86TmExOz2rJdZC/wP root@vm1

Version-Release number of selected component (if applicable):

How reproducible:

Steps to Reproduce:
1.
2.
3.

Actual results:

Expected results:

Additional info:

**Comment by gluster-ant** [comment]
Time: 20190522T06:00:41
dkhandel at redhat commented: 
Misc, can you please take a look at it.

**Comment by gluster-ant** [comment]
Time: 20190612T12:09:44
mscherer at redhat commented: 
Ok so before opening a account, I would like to discuss the plan for automating that.
I kinda feel unease of the fact we are still doing everything manually (especially after the nfs ganesha issue that we found internally), and while I do not have personnaly the ressources nor time to automate (was on TODO list, but after Nigel departure and the migration to AWS, this was pushed down the line), I would like to take on this opportunity to first discuss that, and then open the account. 

In that order, because experience show that the reverse order is not consecutive of any action (curiously, folks listen to me more when they wait on me for something, so I hope folks will excuse me for that obvious blackmail, but ot should be quick).

So, how long would it take to automate the release from Jenkins to download.gluster, and who would be dedicated on it on the gluster side ?
(once we agree on a deadline, I will create a account that expire automatically after that time, just to make sure we do not leave a gapping hole open)

**Comment by gluster-ant** [comment]
Time: 20190613T11:29:02
sacharya at redhat commented: 
Hi Misc,

We have built the debian packages for glusterfs 6.2, and waiting for the creation of accounts to upload the packages. Here, https://github.com/gluster/glusterfs/issues/683 is a github issue, asking reasons for delay on the same. It will be helpful if we are unblocked by this soon. Can you do the needful?

About automating the procedure, I will initiate a discussion with the team, and get back to you.

**Comment by gluster-ant** [comment]
Time: 20190613T11:58:51
mscherer at redhat commented: 
Sure give me a deadline, and I will create the account. I mean, I do not even need a precise one.

Would you agree on "We do in 3 months", in which case I create the account right now (with expiration as set).

(I need a public ssh key and a username)

**Comment by gluster-ant** [comment]
Time: 20190613T13:08:57
kkeithle at redhat commented: 
(In reply to M. Scherer from comment #2)
> Ok so before opening a account, I would like to discuss the plan for
> automating that.
> I kinda feel unease of the fact we are still doing everything manually
> (especially after the nfs ganesha issue that we found internally), and while
> I do not have personnaly the ressources nor time to automate (was on TODO
> list, but after Nigel departure and the migration to AWS, this was pushed
> down the line), I would like to take on this opportunity to first discuss
> that, and then open the account. 
> 
> In that order, because experience show that the reverse order is not
> consecutive of any action (curiously, folks listen to me more when they wait
> on me for something, so I hope folks will excuse me for that obvious
> blackmail, but ot should be quick).
> 
> So, how long would it take to automate the release from Jenkins to
> download.gluster, and who would be dedicated on it on the gluster side ?
> (once we agree on a deadline, I will create a account that expire
> automatically after that time, just to make sure we do not leave a gapping
> hole open)

You, NIgel, and I had a discussion in Berlin over two years ago about this and Nigel was supposed to automate it in Jenkins.

Someone like Sankarshan will have to identify a resource for doing the work now.

**Comment by gluster-ant** [comment]
Time: 20190613T13:17:00
mscherer at redhat commented: 
Yup, but clearly, as long as someone was doing the job manually, this was set as a lesser priority than a lot of things (like fixing the fires all over the place). The increasing backlog of tasks do not make me think we can do it without someone taking ownership of that, and as you rightfully point, that's something we all want since more than 2 years :/

**Comment by gluster-ant** [comment]
Time: 20190822T11:46:33
sacharya at redhat commented: 
@misc (In reply to M. Scherer from comment #4)
> Sure give me a deadline, and I will create the account. I mean, I do not
> even need a precise one.
> 
> Would you agree on "We do in 3 months", in which case I create the account
> right now (with expiration as set).
> 
> (I need a public ssh key and a username)

We have already taken up the task of automating building and packaging. Details can be found at https://bugzilla.redhat.com/show_bug.cgi?id=1727727. 

Please create the account.
Below are the required details:
Public ssh key: 
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCifwFXjkLXFwnlTBMXFgTEHAA1Vavzti41B4Yp1RJYtCuJ91s+P5YHc2j4a/wpVquPJboNuv9wtqknmd5SJYBXB11dinNfHfvE+gCN9Osdn64/om9i3pIpQQeY6uvF4MF9yfyx8huEWFZeaOiljvmTZ3//4kzsJHK2yKCmJFhy5Zcg9+WMM2bjfACjlFDIuOG2kqaRM8tGggOQG9iQ/VElWOTxJkHUJaP50PWdwEHHoiCKmipe5xEcSR/6qubaF6VpMfBLmrjmJMqkjVozryVweHBLn3oQfOkJmlErwJox7hLFuk5V4fvVine5xrWKygw/kA2Mpr7Q1zXg5moZHbCP root@localhost.localdomain

User name: sacharya

**Comment by gluster-ant** [comment]
Time: 20190822T12:01:02
mscherer at redhat commented: 
As said in the comment #2 and comment #4, what is the deadline for the account closure ? 

If I do not get a answer, then I will just decide on "3 month after the creation" and then deploy.

**Comment by gluster-ant** [comment]
Time: 20190822T12:05:54
sacharya at redhat commented: 
Hari, Can you please address the above query?

**Comment by gluster-ant** [comment]
Time: 20190822T13:01:23
hgowtham at redhat commented: 
We are trying to finish it within this sprint (each sprint is for 3 weeks).
So we will assume that we should be done in a month with the automation.

**Comment by gluster-ant** [comment]
Time: 20190822T13:05:37
mscherer at redhat commented: 
ok so 3 months is enougn (cause i also do not want to push unrealisitic deadline or more pressure, plus shit happen), I will add the account as soon as the previous ansible run finish. And if that's not enough, we can of course keep it open longer, just to be clear. But after jenkins issue last month, and the old compromise last time, we can't let stuff open too long if they are not going to clean themself.

**Comment by gluster-ant** [comment]
Time: 20190822T14:26:44
mscherer at redhat commented: 
I created the user, tell me if it doesn't work. The server is download.rht.gluster.org (not download.gluster, who is a proxy).

**Comment by gluster-ant** [comment]
Time: 20191211T12:44:28
sacharya at redhat commented: 
Hi Misc, 

We are almost done with the automation work. It may take a while for completion. Please revive the the account for 3 more months, as we need to upload the packages on scheduled dates.

**Comment by gluster-ant** [comment]
Time: 20191211T12:50:33
hgowtham at redhat commented: 
I have been working on the requirement for automation here (https://github.com/harigowtham/ubuntu-debian-build-glusterfs) as of now. 
Will send it to gerrit once i feel its in a state to review.

Need to work on the signing the packages and the ansible file to get the builder machine ready.

**Comment by gluster-ant** [comment]
Time: 20191211T13:51:46
mscherer at redhat commented: 
ok, done, I extended to 3 mor emonths, so around march.

**Comment by gluster-ant** [comment]
Time: 20191212T04:24:08
spamecha at redhat commented: 
Hi misc, 

As shwetha and me are handling package building together, Please create the account for me as well so that whole load will not be on her and in her absence we won't be blocked

Below are the required details:
Public ssh key: 
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDHKKTwASBKVg4nN3p1vUj87906qFi8KQb/gTmt7ITPDg1GAvVhMJhbC4pT58/k9YjDf2Ez07VZ7fTYs9hqWHF4ZsJ2rbO2MPaHl4Fnfb8MP+Wq33juiznKRZU9+TRTFt83rDoRjDFwzhfGt6zdBPam6Etu0mR55OvWg8XM35wbdW0OP/pjIdQdjVoDp+YdpaX43lCr3M80NsbjAxk7xcPTrpqAK90qpVw1C5mqwHNeqJIGK/enADhaDaMhBPoNpWK1cy5xMnJcBbYXjrUZ4yqmhzJ48yUQiHYzlZZkx4JirbdZzE7FfRZt88crec9KTp1a/GLznP3L0dFA59SWAMKV root@shep-mac 

User name: spamecha

**Comment by gluster-ant** [comment]
Time: 20191212T17:36:55
mscherer at redhat commented: 
ok, that should be done now I wrote a role to handle that.

**Comment by gluster-ant** [comment]
Time: 20191213T02:13:56
sacharya at redhat commented: 
Hi Misc,

Can you create please passwordless login for the accounts or give the temporary password, so that we can change it later. Though the account is created, I am unable to login, because I do not know what the password is.

[sacharya@localhost ~]$ ssh download.rht.gluster.org
sacharya@download.rht.gluster.org's password: 
Permission denied, please try again.

**Comment by gluster-ant** [comment]
Time: 20191213T09:06:07
mscherer at redhat commented: 
Indeed, I need to set password expiration. I did fix for sacharya manually, I need to atumate that. Sorry for forgetting that step, tell me if it work (it will ask for a password on first login, or you can use "passwd" to set the password)

**Comment by gluster-ant** [comment]
Time: 20191213T12:48:53
sacharya at redhat commented: 
It is asking for a password, but I do not know what is the password. If you had set one, please let me know what it is.

**Comment by gluster-ant** [comment]
Time: 20191213T13:54:21
mscherer at redhat commented: 
Mhh, it should let you connect without password, and then "passwd" shouldn't ask for a password. Let me test again, cause I did that using "su", but maybe there is something I missed with openssh.

**Comment by gluster-ant** [comment]
Time: 20191213T13:57:19
mscherer at redhat commented: 
So after adding my ssh key, I was able to connect, and then use "passwd" to set the new password. Can you detail what you did and where it did fail so I can replicate the problem ?

**Comment by gluster-ant** [comment]
Time: 20191213T15:16:13
sacharya at redhat commented: 
I see that I am able to connect now. ssh is allowing me to connect without password. Somehow, it was not the case before.

**Comment by harigowtham** [comment]
Hi Mics and Deepshikha, 
The access given to Shwetha for pushing has expired. Can you please renew it. Along with it if you can give access to the gluster-ant account. we will use the automated script to push the changes as gluster-ant and hence the requirement. I think Sheetal also got the access around the same time. it should expire any time soon. If we can extend the time for that account as well. it would be great. 
Thanks,
Hari.

**Comment by Sheetalpamecha** [comment]
Hi @mscherer and @deepshikhaaa 
The access given to me for pushing on download.gluster.org has expired. Can you please renew it?

**Comment by Shwetha-Acharya** [comment]
Hi @mscherer and @deepshikhaaa 
Please do extend the permission for me(sacharya) as well on download.gluster.org

**Comment by mscherer** [comment]
So I think @Sheetalpamecha and @Shwetha-Acharya account have been renewed (I was on PTO, but git log seems to indicate this was done). 

I am going to close that ticket, cause it start to be a bit messy.
