### ISSUE TITLE
add access to http://download.rht.gluster.org

### ISSUE THREAD

**Issue by Shwetha-Acharya** [gluster/project-infrastructure#142]
user name: sacharya

pub key:
# cat /root/.ssh/id_rsa.pub
```ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDC2jQ6qgV2VQ6pu2yMpsBkvrnga1OuXQrdHhbjNNNXqFQ541JRpIG/e4GGszxwdBAhftfZcYVSU75p0wTT8mh80k/ByDEJrKq+Y0mmLXLIcz0zWUuZRhLVCZsY7pFuvNlaltH+Nw5mK8HFEeyW16ejHR/3o9U2HBkICdtnq12cwKdrHCuxyQpDHV3lkVj9rMshTj6VPV0zf+5+1cTTzkhqju06wYFXH/jS9KUfCOqtotGXQipra/GRBFGC63WzgldKeTLDIP9D5crY1UeAWYCiPwYaObCgb6qI+xiJzcQmx8l4FJVBt4WR/P/keilBHxpPqVQWur2XC7l4T0IE+IeuxO7u8Ko9IYf+IYcrcZt+rySLc+4JXL93CXrjj2VXgyiCwWn8leaFC8NzG78p4ZCTmLHr0gbmMH4udOpy/3VoiRcBd5vsidlT++RhNCp4ivhkRCUrpPly5E8A7w+ZQiaVuo6inSIY1Jr0EB/nm8aGYQBNB8BkZQmYtrPXoVGHTz0= root@sacharya.remote.csb```

**Comment by Shwetha-Acharya** [comment]
@deepshikhaaa

**Comment by mscherer** [comment]
I see you already have access, can you be more specific ?

**Comment by Shwetha-Acharya** [comment]
> I see you already have access, can you be more specific ?

Hi @mscherer I had to change my laptop, so asking for the access with new pub key. Had discussed internally with @deepshikhaaa

**Comment by deepshikhaaa** [comment]
@mscherer Please review and merge https://github.com/gluster/gluster.org_ansible_configuration/pull/63

**Comment by mscherer** [comment]
Done
