### ISSUE TITLE
account expired at download.rht.gluster.org

### ISSUE THREAD

**Issue by Shwetha-Acharya** [gluster/project-infrastructure#143]
[root@sacharya ~]# scp /stretch-apt-amd64-9.4.tgz sacharya@download.rht.gluster.org:/var/www/scratch/
Your account has expired; please contact your system administrator
Connection closed by 8.43.85.175 port 22
lost connection
[root@sacharya ~]#

Please revive this account

**Comment by Shwetha-Acharya** [comment]
@deepshikhaaa @mscherer

**Comment by mscherer** [comment]
Should be ok now, can you test and close the ticket if that's ok ?

**Comment by Shwetha-Acharya** [comment]
closing as the issue is resolved
