### ISSUE TITLE
files under var/log/glusterfs missing:  https://github.com/gluster/glusterfs/pull/2945 

### ISSUE THREAD

**Issue by Shwetha-Acharya** [gluster/project-infrastructure#146]
Latest regression details for the above stated PR(https://github.com/gluster/glusterfs/pull/2945) is at:  https://build.gluster.org/job/gh_centos7-regression/1821/

On downloading the glusterfs-logs.tgz under the Build Artefacts, the files under var/log/glusterfs are missing.

Actual result:

[root@dhcp43-125 LOGS_1821]# cd var/log/glusterfs/
[root@dhcp43-125 glusterfs]# ls -ls
total 0
[root@dhcp43-125 glusterfs]#

Expected result:

There should be log files of various gluster components inside var/log/glusterfs/

**Comment by mscherer** [comment]
indeed, looking at https://build.gluster.org/job/gh_centos7-regression/1821/console , it seems the logs are erased, then we create the tarball. There is definitly something weird.

**Comment by deepshikhaaa** [comment]
I think this PR should fix it https://github.com/gluster/glusterfs/pull/2958
