### ISSUE TITLE
Upgrade RHEL CI to RHEL 8.5

### ISSUE THREAD

**Issue by mykaul** [gluster/project-infrastructure#152]
See https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/8.5_release_notes/index

**Comment by mscherer** [comment]
I do not think we have a RHEL CI upstream. We run on Centos Stream 8 or Centos 7. Isn't it a ticket for downstream ?

**Comment by mykaul** [comment]
RHEL is available for developers. But CentOS 8 Stream is also an option.

**Comment by mscherer** [comment]
So, given we are running cs8 stream, and are working on regular reboot on another bug, I think this ticket can be closed.
