### ISSUE TITLE
Recent changes are not updated at glusterdocs

### ISSUE THREAD

**Issue by Shwetha-Acharya** [gluster/project-infrastructure#157]
The update is merged https://github.com/gluster/glusterdocs/blob/main/docs/release-notes/9.5.md but it never appears on https://docs.gluster.org/en/latest/.

Also tested by merging some minor changes on other files of doc, they too did not appear on docs.gluster.org
@mscherer

**Comment by mscherer** [comment]
Yup, seems to not be triggered. I manually ask for a build, so the short term issue is fixed, but that's not fixed for now.

**Comment by mscherer** [comment]
Ok so the issue was that due to the migration out and back last december, we lost the hook.

I had to add it back on https://readthedocs.org/dashboard/gluster/integrations 

Let's see if this fix the issue for the next commit (as I already done a manual rebuild).

**Comment by Shwetha-Acharya** [comment]
I see that merged commits are automatically updated to glusterdocs after addition of missing hook.

Tested with commit https://github.com/gluster/glusterdocs/commit/4970fbbb7552d2a66abe17f3ec41f163ff32096e which was automatically updated on https://docs.gluster.org/en/latest/release-notes/10.1/

Thanks @mscherer for quick resolution on this.
