### ISSUE TITLE
Builders require `openssl` command

### ISSUE THREAD

**Issue by xhernandez** [gluster/project-infrastructure#159]
A patch in glusterfs (https://github.com/gluster/glusterfs/commit/a7dc43f533ad4b8ff68bf57704fefc614da65493) requires `openssl` to be installed during build time. However a bug in the detection (fixed here: https://github.com/gluster/glusterfs/pull/3247) make it possible to successfully compile even without the tool, but the resulting executable doesn't work well when certificates are used.

**Comment by mscherer** [comment]
So, can you tell which builder exactly failed, as it is installed on the C7 builders, for example:
```
[root@builder-c7-1 ~]# rpm -q openssl
openssl-1.0.2k-24.el7_9.x86_64
```

**Comment by xhernandez** [comment]
These are some builds that failed because of the missing `openssl` command:

* https://build.gluster.org/job/gh_fedora-smoke/2359/
* https://build.gluster.org/job/gh_strfmt_errors/2705/
* https://build.gluster.org/job/gh_devrpm-fedora/2687/
* https://build.gluster.org/job/gh_devrpm-el7/2731/
* https://build.gluster.org/job/gh_32-bit-build-smoke/2700/

It also seems to be missing in the builder used to generate Debian packages (https://github.com/gluster/glusterfs/issues/3234)

**Comment by mscherer** [comment]
Ok, so that's going to be all over the place. it might requires a few iterations.

So we need /usr/bin/openssl on the system for the devrpm jobs (which I have added), but also it need to be added to the spec file, since it use mock (which is part of the source code). 

As for the debian builder, that's not under our control.

**Comment by xhernandez** [comment]
> Ok, so that's going to be all over the place. it might requires a few iterations.
> 
> So we need /usr/bin/openssl on the system for the devrpm jobs (which I have added), but also it need to be added to the spec file, since it use mock (which is part of the source code).

I'm not familiarized with spec files. I'll try to see how to do that.

> As for the debian builder, that's not under our control.

I though all packages from download.gluster.org were created by us. Who creates this: https://download.gluster.org/pub/gluster/glusterfs/10/10.1/Debian/ ?

**Comment by mscherer** [comment]
For the spec files, I can take a look if needed, but I think that's just adding the right BuildRequires

For the debian package, I mean by "our control" that the builder is not managed by the infra team (because it is internal to RH, for a start). @Shwetha-Acharya should know more.

**Comment by xhernandez** [comment]
> For the spec files, I can take a look if needed, but I think that's just adding the right BuildRequires

I've updated https://github.com/gluster/glusterfs/pull/3247 to also add the BuildRequires line. Now it passes all tests but `32-bit-build`.

**Comment by mscherer** [comment]
Ok that one is easy, should be fixed now.

**Comment by Shwetha-Acharya** [comment]
> For the spec files, I can take a look if needed, but I think that's just adding the right BuildRequires
> 
> For the debian package, I mean by "our control" that the builder is not managed by the infra team (because it is internal to RH, for a start). @Shwetha-Acharya should know more.

yes, for debain we use a seperate repo. control file has ssl marked to be required: https://github.com/gluster/glusterfs-debian/blob/bionic-glusterfs-10/debian/control#L22

**Comment by xhernandez** [comment]
> > For the spec files, I can take a look if needed, but I think that's just adding the right BuildRequires
> > For the debian package, I mean by "our control" that the builder is not managed by the infra team (because it is internal to RH, for a start). @Shwetha-Acharya should know more.
> 
> yes, for debain we use a seperate repo. control file has ssl marked to be required: https://github.com/gluster/glusterfs-debian/blob/bionic-glusterfs-10/debian/control#L22

`libssl-dev` doesn't install the `openssl` command line tool. The `openssl` package needs to be explicitly specified.

**Comment by Shwetha-Acharya** [comment]
I have also added openssl explicitly to debian control files: https://github.com/gluster/glusterfs-debian/commit/012955f4f792172c549e178f13f51a06b710f4cb, https://github.com/gluster/glusterfs-debian/commit/877ac0a7e6663165bda6917fde6fd08984ef930e, https://github.com/gluster/glusterfs-debian/commit/c31e31a8a15fa61f6a8fcd2704242647d6435513
