### ISSUE TITLE
[bug:1348072] Backups for Gerrit

### ISSUE THREAD

**Issue by gluster-ant** [gluster/project-infrastructure#16]
URL: https://bugzilla.redhat.com/1348072
Creator: nigelb at redhat
Time: 20160620T05:59:49

We don't currently backup Gerrit. We should starting backing it up ASAP considering it's critical infrastructure.

**Comment by gluster-ant** [comment]
Time: 20160802T03:57:02
nigelb at redhat commented: 
This is blocked on having more disk space on the machine. I've brought this up with Michael. Once we move the VM over, we'll add more diskspace.

**Comment by gluster-ant** [comment]
Time: 20170830T19:12:14
mscherer at redhat commented: 
So, what is needed to be backed up exactly ? Postgresql should be ok now, what else ?

**Comment by gluster-ant** [comment]
Time: 20170831T02:12:35
nigelb at redhat commented: 
We'll need to backup /review/review.gluster.org/ entirely. And time it so it's at the exact same time as the postgresql back up. Extra points for switching off apache and xinetd during the duration of the back up (so that gerrit is effectively read-only)

**Comment by gluster-ant** [comment]
Time: 20190509T19:53:35
atumball at redhat commented: 
Any idea if this is done?

**Comment by gluster-ant** [comment]
Time: 20190527T01:00:54
sankarshan at redhat commented: 
Michael, is this being planned in the near future?

**Comment by gluster-ant** [comment]
Time: 20190612T12:16:11
mscherer at redhat commented: 
I need to review the current status, I know we have database backups, but backups is one half of the coin, we also need to test the recovery from end to end. And testing the recovery requires to be able to automate the installation of Gerrit, something that was cautiously delayed due to the criticity of the service (aka, that's still not managed by ansible).

**Comment by mscherer** [comment]
As we moved out of gerrit, this bug can be closed
