### ISSUE TITLE
Permission to create public repositories on gluster

### ISSUE THREAD

**Issue by Shwetha-Acharya** [gluster/project-infrastructure#161]
I am unable to tranfer my private repo into a public repo on Gluster.org

On trying to tranfer the repo: 
I am greeted with the warning "You don’t have the permission to create public repositories on gluster"

@rakshithakamath94 @mscherer

**Comment by deepshikhaaa** [comment]
Can you please transfer the ownership of that repo to me?

**Comment by Shwetha-Acharya** [comment]
I have requested for the repository transfer, on your approval, it will be transferred @deepshikhaaa

**Comment by deepshikhaaa** [comment]
Moved the repo to https://github.com/gluster/upstream-glusterfs-builds
