### ISSUE TITLE
Requesting merge access to gluster/glusterdocs

### ISSUE THREAD

**Issue by black-dragon74** [gluster/project-infrastructure#164]
I have submitted quite a lot of [patches](https://github.com/gluster/glusterdocs/pulls?q=is%3Apr+author%3Ablack-dragon74) regarding feature addition and site overhaul to the docs site. I have time and skills needed to maintain this project.

As the original maintainers of the Glusterdocs no longer work with us, can I have the rights to merge/review the PRs.

Doing so will speed up the development workflow as right now someone from gluster core eng has to do that in their free time.

Please let me know if some additional info is required.

CC: @deepshikhaaa @mscherer

Regards

**Comment by mscherer** [comment]
Done. Sorry to not have done earlier, i was out .

**Comment by black-dragon74** [comment]
Thank you!
