### ISSUE TITLE
Not able to access softserve web link to create a VM

### ISSUE THREAD

**Issue by mohit84** [gluster/project-infrastructure#166]
When I am pressing the button "Login with github" on https://softserve.gluster.org/ to create a VM, I am getting an error on
web page "The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application."

**Comment by mscherer** [comment]
We are looking on it, but we found a few issue with softserve (for a start, there is some issue with key limits in the DB, and a issue amazon side and my github account because I have 2 keys).

**Comment by mscherer** [comment]
So we diagnosed the issue to be:
```
$ curl -s https://github.com/mohit84.keys | wc -c
4461
```

And there is a limit on 4096 in softserve DB schema. We should remove the limit of course, but in the mean time, can you remove some keys (as I counted 9 ) ?

**Comment by rakshithakamath94** [comment]
https://softserve.gluster.org
