### ISSUE TITLE
extend my login permit on  download.gluster.org

### ISSUE THREAD

**Issue by Shwetha-Acharya** [gluster/project-infrastructure#169]
user name: sacharya
pub key: 
[root@sacharya]# cat /root/.ssh/id_rsa.pub 
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDC2jQ6qgV2VQ6pu2yMpsBkvrnga1OuXQrdHhbjNNNXqFQ541JRpIG/e4GGszxwdBAhftfZcYVSU75p0wTT8mh80k/ByDEJrKq+Y0mmLXLIcz0zWUuZRhLVCZsY7pFuvNlaltH+Nw5mK8HFEeyW16ejHR/3o9U2HBkICdtnq12cwKdrHCuxyQpDHV3lkVj9rMshTj6VPV0zf+5+1cTTzkhqju06wYFXH/jS9KUfCOqtotGXQipra/GRBFGC63WzgldKeTLDIP9D5crY1UeAWYCiPwYaObCgb6qI+xiJzcQmx8l4FJVBt4WR/P/keilBHxpPqVQWur2XC7l4T0IE+IeuxO7u8Ko9IYf+IYcrcZt+rySLc+4JXL93CXrjj2VXgyiCwWn8leaFC8NzG78p4ZCTmLHr0gbmMH4udOpy/3VoiRcBd5vsidlT++RhNCp4ivhkRCUrpPly5E8A7w+ZQiaVuo6inSIY1Jr0EB/nm8aGYQBNB8BkZQmYtrPXoVGHTz0= root@sacharya.remote.csb
[root@sacharya glusterfs]#

**Comment by mscherer** [comment]
so there is a issue with the deployment of the fix, I am looking at it.

**Comment by mscherer** [comment]
done, can you confirm it work ?

**Comment by Shwetha-Acharya** [comment]
@mscherer I am able to ssh to download.gluster.org!
Thanks for the resolution:)
