### ISSUE TITLE
[bug:1807761] Mails to packaging@gluster.org are not being delivered

### ISSUE THREAD

**Issue by gluster-ant** [gluster/project-infrastructure#17]
URL: https://bugzilla.redhat.com/1807761
Creator: ndevos at redhat
Time: 20200227T08:11:23

It seems that emails to the packaging list are not being delivered. There have been release announcements for maintainers and packagers, which only have been delivered at the maintainers list. Both lists were on To:.

Missing February archive:
https://lists.gluster.org/pipermail/packaging/

Emails with packaging on To:
https://lists.gluster.org/pipermail/maintainers/2020-February/006663.html
https://lists.gluster.org/pipermail/maintainers/2020-February/006664.html

Emails to the packaging list have not arrived for me as a subscriber, nor in the archive.

When emails to the packaging list are not delivered, it is likely that nobody builds and/or tests the packages and releases will be delayed.

**Comment by gluster-ant** [comment]
Time: 20200227T20:45:01
mscherer at redhat commented: 
Oups, my fault. 

After a meeting in brno, we did create a packaging@gluster alias and I suspect this did interfer with the list (because the lists are on the same domain. I did remove it, and will see with the team to see what name they want.

**Comment by gluster-ant** [comment]
Time: 20200302T04:51:17
hgowtham at redhat commented: 
Hi,

I think we can use the packing@gluster for notifying people about the packages to be created. We want a email id that gluster ant can use for GitHub. We decided to use gluster ant as this script just needs a common user with GitHub credentials.

**Comment by gluster-ant** [comment]
Time: 20200309T09:03:15
ndevos at redhat commented: 
What is the difference between the packaging@gluster.org list? That list contains packagers from different distributions, they can act on the (early) release notifications and prepare packages before the announcement goes out to the other lists/tweets/...

**Comment by gluster-ant** [comment]
Time: 20200311T10:09:06
mscherer at redhat commented: 
So, since no one remember why, it might just have been me doing out of enthousiams during the hackfest, and I guess i can drop that alias since we have a list.

**Comment by mscherer** [comment]
Closing this bug, as the alias was removed
