### ISSUE TITLE
task 161 pending in https://build.gluster.org/job/release-new/ from ~2 hours

### ISSUE THREAD

**Issue by Shwetha-Acharya** [gluster/project-infrastructure#172]
These tasks normally execute in few seconds, however, they are at pending state from quite sometime now,

with the message:
(pending—All nodes of label ‘[smoke7](https://build.gluster.org/label/smoke7)’ are offline)

Are all the nodes offline for some maintenance? Can we assign any nodes that are up?

@mscherer

**Comment by mscherer** [comment]
Indeed, seems the last jenkins update broke some builders. I am on it.

**Comment by Shwetha-Acharya** [comment]
Task 161 is now complete!
