### ISSUE TITLE
Softserve maximum lease time is too short

### ISSUE THREAD

**Issue by xhernandez** [gluster/project-infrastructure#174]
The maximum time a softserve machine can be allocated is 4 hours. This is not enough even to run a single full regression test, and completely insufficient if you additionally need to debug something.

Could the maximum time be increased at lest to 8 or 12 hours ?

**Comment by mscherer** [comment]
Sure, seems like a good idea, I discussed with @rakshithakamath94 and she is looking on it.

**Comment by rakshithakamath94** [comment]
We have now increased the procurement time to 8 hours.

PR : https://github.com/gluster/softserve/pull/68

**Comment by rakshithakamath94** [comment]
Closing the issue.

**Comment by xhernandez** [comment]
Thanks !
