### ISSUE TITLE
Unable to edit specific content in https://www.gluster.org

### ISSUE THREAD

**Issue by Shwetha-Acharya** [gluster/project-infrastructure#175]
Unable to access 'Active Releases' and 'Archived Releases' part of the  https://www.gluster.org/release-schedule/ from https://www.gluster.org/wp-admin/edit.php?post_type=page&mode=excerpt

@mscherer

**Comment by Shwetha-Acharya** [comment]
@mscherer Did you get time to check this issue?

**Comment by jasonbrooks** [comment]
@Shwetha-Acharya  On the page https://www.gluster.org/wp-admin/post.php?post=8780&action=edit, there's an element called Releases, and there are left and right tabs for that element. Left is the default selected tab, but if you click the Right tab, you should see the Active Releases and Archived Releases content.

**Comment by Shwetha-Acharya** [comment]
Ohh! 
Thanks @jasonbrooks for helping me with this!
Closing the issue as resolved.
