### ISSUE TITLE
Jobs scanned for fstat.gluster.org should be updated

### ISSUE THREAD

**Issue by xhernandez** [gluster/project-infrastructure#184]
I think we should add `centos8-s390-regression` and `gh-regression-on-demand-full-run` to the jobs monitored for failures in fstat.gluster.org. Probably it would also be better to remove old jobs not used any more (even from Jenkins).

**Comment by mscherer** [comment]
From what I see in the code, there is no specific filtering on job being done. So not sure where to add anything.

**Comment by xhernandez** [comment]
Based on the `readme.md` from the repo:

## Using fstat
- Run migrations and setup database ``` python manage.py db upgrade ```
- To serve the fstat app on localhost run ``` python manage.py runserver ```
- Create application.cfg and add ``` DEBUG=True ``` to it to enable debug mode for your flask app.
- To fetch failures from build.gluster.org run ``` python manage.py proccess_jobs -n <number_of_days> -j <job_name> ```
- By default fstat reads and writes the data into sqlite but it can be overriden in your application.cfg.

So the application itself is not collecting the data, but some task should be running periodically to collect data from the selected jobs using the `manage.py` script. Isn't there any cron job or similar that triggers a set of those commands ?

**Comment by mscherer** [comment]
We have that:

https://github.com/gluster/gluster.org_ansible_configuration/blob/master/roles/fstat/tasks/main.yml#L91-L102

So indeed, that's done outside of code, and outside of a config file.

**Comment by mscherer** [comment]
So, adding 2 jobs, ok, but which one should we remove ?

**Comment by xhernandez** [comment]
> We have that:
> 
> https://github.com/gluster/gluster.org_ansible_configuration/blob/master/roles/fstat/tasks/main.yml#L91-L102
> 
> So indeed, that's done outside of code, and outside of a config file.

I did miss that part. Thanks for pointing it out.

> So, adding 2 jobs, ok, but which one should we remove ?

It seems that the list already contains only the active jobs. Probably the old jobs I saw in fstat are there just because we have old data in the DB. That's fine. There's no need to remove any job IMO.

**Comment by mscherer** [comment]
ok, so as I added 2 more jobs, I can close that bug, but as usual, feel free to reopen it if I misunderstood.
