### ISSUE TITLE
[bug:1805186] Centos Regression failing with ENOSPC.

### ISSUE THREAD

**Issue by gluster-ant** [gluster/project-infrastructure#2]
URL: https://bugzilla.redhat.com/1805186
Creator: ypadia@redhat
Time: 20200220T13:13:02

Description of problem: Centos Regression is failing on all the patches with error "mkdir: cannot create directory ‘/build/scratch’: No space left on device".

Actual results:
Centos Regression fails

Expected results:
Centos Regression should pass.

Additional info:
Link to the output console: https://build.gluster.org/job/centos7-regression/9451/console

**Comment by gluster-ant** [comment]
Time: 20200220T14:31:31
mscherer@redhat commented: 
builder204 is indeed full, Deepshika did disconnect it.

[root@builder204 backends]# du -sh *
11M	brick1
3,7G	brick2
6,3G	brick3
8,0K	patchy1
6,3G	patchy2
6,3G	patchy3
[root@builder204 backends]# pwd
/d/backends


Not sure why this wasn't cleaned sooner.

**Comment by gluster-ant** [comment]
Time: 20200224T12:54:05
ravishankar@redhat commented: 
Smoke also fails with ENOSPC now:
https://build.gluster.org/job/devrpm-fedora/19527/consoleFull
https://build.gluster.org/job/devrpm-fedora/19525/console

**Comment by gluster-ant** [comment]
Time: 20200224T13:45:29
mscherer@redhat commented: 
 builder48.int.rht.gluster.org seems to be full. Seems notification did disappear from my mail box :/ 
I am cleaning it.

**Comment by gluster-ant** [comment]
Time: 20200225T04:20:22
dkhandel@redhat commented: 
Misc, not just builder48 is full. Builder45 and builder47 seems to be full as well and that is the reason 32-bit-build smoke job is failing https://build.gluster.org/job/32-bit-build-smoke/6723/ during the installation of packages.

**Comment by gluster-ant** [comment]
Time: 20200225T09:40:10
mscherer@redhat commented: 
Seems the issue is caused by mock cache, due to older fedora cache (F28, F29) who do not get cleaned automatically. Not sure if that's safe to automate.

**Comment by gluster-ant** [comment]
Time: 20200225T09:48:49
mscherer@redhat commented: 
on builder47, seems the logs are not rotated, not sure why.

**Comment by mscherer** [comment]
No longer a issue, will reopen if it happen again
