### ISSUE TITLE
[bug:1489325] Place to host gerritstats

### ISSUE THREAD

**Issue by gluster-ant** [gluster/project-infrastructure#24]
URL: https://bugzilla.redhat.com/1489325
Creator: nigelb at redhat
Time: 20170907T08:31:59

We need a place to host Gerrit Stats. It can be on a location that's shared with other things, for instance, I don't mind staticanalysis, logs, and this ending up in the same place. This can be behind the cage internal network and proxied to the internet.

**Comment by gluster-ant** [comment]
Time: 20181012T16:31:16
atumball at redhat commented: 
Would be good to get this online sometimes in coming months!

**Comment by gluster-ant** [comment]
Time: 20190527T03:43:51
dkhandel at redhat commented: 
I need more info about this bug. What kind of stats do we want? What would be the end result of this?

It will be altogether a hosted service. We can have it in the cage or on the same as gerrit machine.

@misc thoughts?

**Comment by gluster-ant** [comment]
Time: 20190612T10:54:39
mscherer at redhat commented: 
I would prefer it in the cage, on a separate VM (I already started the playbook). As for the stats and end results, that should be to the reporter, not me.

**Comment by mscherer** [comment]
We no longer use gerrit, so closing that one
