### ISSUE TITLE
[bug:1504713] Move planet build to be triggered by Jenkins

### ISSUE THREAD

**Issue by gluster-ant** [gluster/project-infrastructure#26]
URL: https://bugzilla.redhat.com/1504713
Creator: mscherer at redhat
Time: 20171020T13:09:59

Right now, planet.gluster.org is built on webbuilder.int.gluster.org. It occured to me that using Jenkins would increase transparency, I have submitted some change for that upstream (aka, the OSAS repo):

https://github.com/OSAS/ansible-role-web_builder/pull/19

Then gluster side, we would just need to add the ssh key of jenkins on the builder, and have it run the script when the repository is change and/or on a regular cadence.

Then in turn, this would let people look from time to time to the log and see if there is issues.

**Comment by gluster-ant** [comment]
Time: 20171020T13:12:53
mscherer at redhat commented: 
I also wonder if we could integrate jenkins with github, to replace the travis build. It tend to change underneat us and may surprise users.

Ideally, I also would like a system that open ticket when a feed fail for too long.

**Comment by gluster-ant** [comment]
Time: 20190527T01:52:40
sankarshan at redhat commented: 
(In reply to M. Scherer from comment #1)
> I also wonder if we could integrate jenkins with github, to replace the
> travis build. It tend to change underneat us and may surprise users.
> 
> Ideally, I also would like a system that open ticket when a feed fail for
> too long.

Is this now in place? The last time I checked with Deepshikha, there was a refrain of the cron behind the planet scripts failing randomly.

**Comment by gluster-ant** [comment]
Time: 20190612T11:02:21
mscherer at redhat commented: 
Nope, nothing changed. That's kinda a lower priority, since the system work well enough most of the time, and has a rather low impact.

**Comment by mscherer** [comment]
So, I finally did it:

https://review.gluster.org/#/c/build-jobs/+/24216/

**Comment by mscherer** [comment]
closing, since that's done
