### ISSUE TITLE
[bug:1623596] Git plugin might be suffering from memory leak

### ISSUE THREAD

**Issue by gluster-ant** [gluster/project-infrastructure#33]
URL: https://bugzilla.redhat.com/1623596
Creator: ykaul at redhat
Time: 20180829T17:32:27

Description of problem:
It provides a warning and a hint to look at https://wiki.jenkins.io/display/JENKINS/Remove+Git+Plugin+BuildsByBranch+BuildData to workaround it.

**Comment by gluster-ant** [comment]
Time: 20180829T19:59:24
mscherer at redhat commented: 
So, that do not seems like a memory leak, but that would solve our disk space issue in a elegant way. It should also solve by itself with 3.0 version of the git plugin, currently in beta.

I guess we can first clean the branch with the groovy script, that would give use some more breathing room, and later wait for the upgrade ?

**Comment by gluster-ant** [comment]
Time: 20181003T09:20:28
nigelb at redhat commented: 
Adding the Github link to track the pull request which fixes this.

**Comment by mscherer** [comment]
We are using a new plugin, closing this one
