### ISSUE TITLE
[bug:1638030] Need a regression job to test out Py3 support in Glusterfs code base

### ISSUE THREAD

**Issue by gluster-ant** [gluster/project-infrastructure#35]
URL: https://bugzilla.redhat.com/1638030
Creator: srangana at redhat
Time: 20181010T13:55:55

Description of problem:

With the move towards Python3 we need a regression job (nightly initially) that exercises the tests on a platform that is Python3 by default.

Current regression on CentOS7 uses Python2 and to ensure we are working on both versions of Python we need a new job for Python3, and later as we move up CentOS versions or the default platform moves to Python3 we need to retain a Python2 regression job against an older platform till we support the same (this is just a note for later).

The tests can be filtered out to just run those that utilize Python code in the code base, but to start with let us get a full regression and once the pared down list is complete, we can reduce the scope of the job.

**Comment by gluster-ant** [comment]
Time: 20181011T11:59:50
mscherer at redhat commented: 
So, any version of python3 would do the trick, or do we have one in mind ?

**Comment by gluster-ant** [comment]
Time: 20181011T12:27:35
kkeithle at redhat commented: 
survey of the platforms I build gluster for have:

rhel8: 3.6.6
fedora 30 (rawhide): 3.7
fedora 29: 3.7
fedora 28: 3.6.6
debian 10 (buster/sid): 3.6.7rc1
debian 9: 3.5.3
debian 8¹: 3.4.2
ubuntu 16.04 (xenial): 3.5.2
ubuntu 18.04 (bionic): 3.6.4+
ubuntu 18.10 (cosmic): 3.6.6
centos7 (w/ EPEL)²: 3.4.9 or 3.6.6

¹ We will not be building gluster-5 packages on debian 8.

² Information only. The packages in the CentOS Storage SIG will not use EPEL and will be python2.)

I'm not a python expert but I'd be inclined to be aggressive and use 3.7; 3.6.6 would be the lowest version I'd be interested in.

I have to wonder if rhel8 will update to 3.7 before it ships.

My 2¢

**Comment by gluster-ant** [comment]
Time: 20181015T02:19:02
nigelb at redhat commented: 
Going to target this for Sprint 5.

**Comment by mscherer** [comment]
Given we run test on c8, the python 3 part should be dealt with, so closing
