### ISSUE TITLE
[bug:1659934] Cannot unsubscribe the review.gluster.org

### ISSUE THREAD

**Issue by gluster-ant** [gluster/project-infrastructure#36]
URL: https://bugzilla.redhat.com/1659934
Creator: roidinev at gmail
Time: 20181217T08:56:07

Description of problem:

https://review.gluster.org/settings/
Cannot find where to unsubscribe the mail.

Can remove notification,but also receive email

Version-Release number of selected component (if applicable):

How reproducible:

Steps to Reproduce:
1.
2.
3.

Actual results:

Expected results:

Additional info:

**Comment by gluster-ant** [comment]
Time: 20190527T01:56:12
sankarshan at redhat commented: 
(In reply to baul from comment #0)
> Description of problem:
> 
> https://review.gluster.org/settings/
> Cannot find where to unsubscribe the mail.
> 
> Can remove notification,but also receive email

"Email notifications" changed to "None" - does that work?

**Comment by gluster-ant** [comment]
Time: 20191209T03:32:54
roidinev at gmail commented: 
No, "Email notifications" changed to "None" - does not  work.

**Comment by gluster-ant** [comment]
Time: 20200221T04:20:05
roidinev at gmail commented: 
In the review.gluster.org,settings--profile--email address set as empty.
                          settings--Preferences--"Email notifications" changed to "None"
                          settings---Watched Projects--none
                          settings---Contact Information--Preferred Email(not set)

                          man menu--my --Watched Changes (nothings show).

And also receive email.

**Comment by gluster-ant** [comment]
Time: 20200224T12:53:47
mscherer at redhat commented: 
What notification are you getting ? I do not think we found a way to disable all notifications, since some are done based on the patch email. We can filter that on the SMTP level however.

**Comment by gluster-ant** [comment]
Time: 20200224T13:47:47
roidinev at gmail commented: 
subject as ‘Change in glusterfs[release-5]: cluster/ec: Always read from good-mask’ from 
Gluster Build System (Code Review) <review@review.gluster.org>

**Comment by gluster-ant** [comment]
Time: 20200224T13:53:23
mscherer at redhat commented: 
What does the notification contain ? I am not that familliar with the gerrit notification to recognize where do they come from exactly.

**Comment by gluster-ant** [comment]
Time: 20200224T14:32:36
roidinev at gmail commented: 
https://review.gluster.org/#/c/glusterfs/+/24020/
see ,
the history on the page is received.

**Comment by gluster-ant** [comment]
Time: 20200224T14:44:49
mscherer at redhat commented: 
ok, can you send me a copy of the email with the headers (or attach it here), cause I am still not able to see what is going on with just that information.

**Comment by gluster-ant** [comment]
Time: 20200224T14:59:44
roidinev at gmail commented: 
Have sent to your mail.  Just omit the ! in the mail where i just block the send ,so have this warning

**Comment by mscherer** [comment]
As review is no longer used, this bug can be closed.
