### ISSUE TITLE
[bug:1711945] create account on download.gluster.org

### ISSUE THREAD

**Issue by gluster-ant** [gluster/project-infrastructure#38]
URL: https://bugzilla.redhat.com/1711945
Creator: spamecha at redhat
Time: 20190520T13:07:35

Description -
To upload the packages 

public key - 

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDaSvn31f+1My0S9aWAvjIWPrVOiENmWrM62CEF/wzBvAnMRuRh0qaGrcrJ1ZKz9+yjetwX7/obuynjjUTd0f/245Jc+f06E66jUJHKGjtk8bwfa0JMUzGYrFVyNFXMPqewRvcHZoFnjZF3xOIbCqTy4H9CZfJZszc83+FLoITPir3HNMJo0ATrSe9XHBRJHne6el+zxfaGQMEe4M5p76oWJORsvYkGjqAEnQSRTbdF9e51VvLz3ME3pdWiPviWF4TIkXolAjD7A2Jm9KK06t9SiOIP9AuVS9llVyf8gOZrwP+IR5gbZeiL5+9G+xWQTi7Pw5anAfJY1Mbe2l31yAen root@server1

**Comment by gluster-ant** [comment]
Time: 20190823T03:58:27
spamecha at redhat commented: 
Hi Michael

Please create the account for me as well.
Below are the required details:
Public ssh key: 

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDHKKTwASBKVg4nN3p1vUj87906qFi8KQb/gTmt7ITPDg1GAvVhMJhbC4pT58/k9YjDf2Ez07VZ7fTYs9hqWHF4ZsJ2rbO2MPaHl4Fnfb8MP+Wq33juiznKRZU9+TRTFt83rDoRjDFwzhfGt6zdBPam6Etu0mR55OvWg8XM35wbdW0OP/pjIdQdjVoDp+YdpaX43lCr3M80NsbjAxk7xcPTrpqAK90qpVw1C5mqwHNeqJIGK/enADhaDaMhBPoNpWK1cy5xMnJcBbYXjrUZ4yqmhzJ48yUQiHYzlZZkx4JirbdZzE7FfRZt88crec9KTp1a/GLznP3L0dFA59SWAMKV root@shep-mac

User name: spamecha

**Comment by Sheetalpamecha** [comment]
Hi @mscherer and @deepshikhaaa 
My access for pushing at download.gluster.org has been expired. Can you please extend the time for this account?

**Comment by mscherer** [comment]
This was pushed.

**Comment by Shwetha-Acharya** [comment]
Hi @mscherer and @deepshikhaaa
My access for pushing at download.gluster.org is also expired. Please extend the permissions for the account: sacharya.

Pub key: 
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCifwFXjkLXFwnlTBMXFgTEHAA1Vavzti41B4Yp1RJYtCuJ91s+P5YHc2j4a/wpVquPJboNuv9wtqknmd5SJYBXB11dinNfHfvE+gCN9Osdn64/om9i3pIpQQeY6uvF4MF9yfyx8huEWFZeaOiljvmTZ3//4kzsJHK2yKCmJFhy5Zcg9+WMM2bjfACjlFDIuOG2kqaRM8tGggOQG9iQ/VElWOTxJkHUJaP50PWdwEHHoiCKmipe5xEcSR/6qubaF6VpMfBLmrjmJMqkjVozryVweHBLn3oQfOkJmlErwJox7hLFuk5V4fvVine5xrWKygw/kA2Mpr7Q1zXg5moZHbCP root@localhost.localdomain

**Comment by Shwetha-Acharya** [comment]
@mscherer @deepshikhaaa  Please revive the permission at download.rht.gluster.org
