### ISSUE TITLE
[bug:1463273] infra: include bugzilla query in the weekly BZ email

### ISSUE THREAD

**Issue by gluster-ant** [gluster/project-infrastructure#42]
URL: https://bugzilla.redhat.com/1463273
Creator: kkeithle at redhat
Time: 20170620T13:20:55

Description of problem:

That way maintainers can run their own query in between the weekly email (without having to guess what the bugzilla query should be.)

Version-Release number of selected component (if applicable):

How reproducible:

Steps to Reproduce:
1.
2.
3.

Actual results:

Expected results:

Additional info:

**Comment by amarts** [comment]
This can now change into github query, as there are no more bugzilla bugs.

**Comment by mscherer** [comment]
I am closing, since there is no more bugzilla mail. If we want a weekly mail for github, please open a new bug (or a PR is even better, we can run code somewhere)
