### ISSUE TITLE
Regression is failing due to space issue on build server

### ISSUE THREAD

**Issue by mohit84** [gluster/project-infrastructure#47]
Test regression is failing due to space issue on build server
https://build.gluster.org/job/centos7-regression/9841/consoleFull

**Comment by mscherer** [comment]
Seems /d/backends took 10G, with 6G for /d/backends/brick3. I wiped all, I guess that was a left over.

**Comment by mscherer** [comment]
I did cleaned the server, an bringed it back online (didn't see it was set offline)
