### ISSUE TITLE
Request gerrit dashboard addition for release 8

### ISSUE THREAD

**Issue by rkothiya** [gluster/project-infrastructure#48]
Release 8 is about to be branched. Towards this, we would require a gerrit dashboard for this release @ https://review.gluster.org/#/admin/projects/glusterfs,dashboards 

This bug is a request for the same.

Release version: 8

**Comment by deepshikhaaa** [comment]
Dashboard for release 8 has been created.
https://review.gluster.org/#/projects/glusterfs,dashboards/dashboard:8-dashboard
