### ISSUE TITLE
Need permission to created the Release8 branch 

### ISSUE THREAD

**Issue by rkothiya** [gluster/project-infrastructure#49]
While trying to push the release-8 branch getting the following error, need permission to push this. 

$ git push --tags origin release-8
Counting objects: 5, done.
Delta compression using up to 2 threads.
Compressing objects: 100% (5/5), done.
Writing objects: 100% (5/5), 641 bytes | 641.00 KiB/s, done.
Total 5 (delta 2), reused 0 (delta 0)
remote: Resolving deltas: 100% (2/2)
remote: Processing changes: refs: 2, done    
To ssh://review.gluster.org/glusterfs.git
 * [new tag]             v9dev -> v9dev
 ! [remote rejected]     release-8 -> release-8 (prohibited by Gerrit: update for creating new commit object not permitted)
 ! [remote rejected]     v8.0alpha -> v8.0alpha (prohibited by Gerrit: update for creating new commit object not permitted)
error: failed to push some refs to 'ssh://rkothiya@review.gluster.org/glusterfs.git'

**Comment by deepshikhaaa** [comment]
Can you please try now?

**Comment by rkothiya** [comment]
I got the following error this time : 

$ git push --tags origin release-8
Counting objects: 4, done.
Delta compression using up to 2 threads.
Compressing objects: 100% (4/4), done.
Writing objects: 100% (4/4), 496 bytes | 496.00 KiB/s, done.
Total 4 (delta 2), reused 0 (delta 0)
remote: Resolving deltas: 100% (2/2)
remote: Processing changes: refs: 1, done    
To ssh://review.gluster.org/glusterfs.git
 * [new branch]          release-8 -> release-8
 ! [remote rejected]     v8.0alpha -> v8.0alpha (prohibited by Gerrit: update for creating new commit object not permitted)
error: failed to push some refs to 'ssh://rkothiya@review.gluster.org/glusterfs.git'

**Comment by rkothiya** [comment]
I pushed the tag separately again and it worked this time : 

$ git push origin v8.0alpha
Counting objects: 1, done.
Writing objects: 100% (1/1), 179 bytes | 179.00 KiB/s, done.
Total 1 (delta 0), reused 0 (delta 0)
remote: Processing changes: done    
To ssh://review.gluster.org/glusterfs.git
 * [new tag]             v8.0alpha -> v8.0alpha

**Comment by rkothiya** [comment]
The issue can be closed thanks.

**Comment by mscherer** [comment]
Can we document what is needed to create a new branch ? Because we have that, the dashboard, the jenkins job ?

**Comment by mscherer** [comment]
Closing, 8 is EOL
