### ISSUE TITLE
[bug:1657584] Re-enable TSAN jobs

### ISSUE THREAD

**Issue by gluster-ant** [gluster/project-infrastructure#5]
URL: https://bugzilla.redhat.com/1657584
Creator: nigelb at redhat
Time: 20181210T03:20:57

This job is currently running on the builders on the cage and does not seem to have enough memory to run. This ticket is to move them to a machine on Rackspace. Pre-requisites

* New machine on Rackspace with Fedora
* Add machine to Jenkins.
* Change job config to use new machine rather than cage builders
* Potentially share the same builder with ASAN job as well.

**Comment by gluster-ant** [comment]
Time: 20181210T20:59:23
mscherer at redhat commented: 
We are going out of rackspace, so why not just add a builder with more memory ?

**Comment by gluster-ant** [comment]
Time: 20181217T06:32:35
nigelb at redhat commented: 
I'd like to move regression jobs out of the cage as far as possible. They're noisy neighbors. Also happy to block this until we have a new hosting provider.

**Comment by mscherer** [comment]
Closing in favor of #68
