### ISSUE TITLE
Add a nightly build verification job in Jenkins for release-8

### ISSUE THREAD

**Issue by rkothiya** [gluster/project-infrastructure#51]
Please add a nightly build verification job in Jenkins for release-8

**Comment by rakshithakamath94** [comment]
Hi @rkothiya ,

Can you please give me bit more detail please.

Thanks,
Rakshitha Kamath

**Comment by rkothiya** [comment]
you can refer to the below bug:
https://bugzilla.redhat.com/show_bug.cgi?id=1678378

**Comment by mscherer** [comment]
Closing 8 is EOL.
