### ISSUE TITLE
Increase nightly regression job frequency for centos 8

### ISSUE THREAD

**Issue by sunilheggodu** [gluster/project-infrastructure#52]
Please increase the nightly regression job frequency to two days once.

**Comment by rakshithakamath94** [comment]
Hi @sunilheggodu,

A fix have been provided for the above issue. 


Thanks,
RK

**Comment by rakshithakamath94** [comment]
Hi,

There was a small configuration error due to which the build was not happening as expected, now the issue has been resolved.

Thanks,
RK
