### ISSUE TITLE
Need permission to create to repo for ansible collections

### ISSUE THREAD

**Issue by pkesavap** [gluster/project-infrastructure#54]
Repo name:  gluster-ansible-collection
would require admin privileges for the above repo (read,write,modify, and add/remove collaborators).

This repo is required for the migrations of gluster modules to ansible collections , due to removal of gluster modules in ansible from 2.10

**Comment by deepshikhaaa** [comment]
Here you go https://github.com/gluster/gluster-ansible-collection

I've provided you the admin rights for this repo
