### ISSUE TITLE
Smoke failure:Fatal error: can't close cli-rpc-ops.o: No space left on device

### ISSUE THREAD

**Issue by sunnyku** [gluster/project-infrastructure#56]
We see frequent smoke failure on FreeBSD snoke:
- https://build.gluster.org/job/freebsd-smoke/38746/console
- https://build.gluster.org/job/freebsd-smoke/38745/console

**Comment by deepshikhaaa** [comment]
The builder seems out of space. clientmqueue was eating up 1.7G space, blocking so many requests in the queue. Michael did a cleanup in the FreeBSD builder. 

Michael is investigating more on what went wrong with sendmail. Space issue should be fixed.

**Comment by mscherer** [comment]
yeah, but I do not understand why it fail for non space related reason, I did reboot in case, but I also see others failures on other part of the infra, so maybe the issue is on the hypervisor.

**Comment by mscherer** [comment]
Seems stuff are back at normal: https://build.gluster.org/job/freebsd-smoke/38754/

**Comment by sunnyku** [comment]
Thanks Michael.

**Comment by sunnyku** [comment]
Fixed now closing this issue.
