### ISSUE TITLE
glusto build checker is failing with ProxyError('Cannot connect to proxy.', error(111, 'Connection refused'))

### ISSUE THREAD

**Issue by balakreddy** [gluster/project-infrastructure#61]
pylint check on build.gluster.org is failing continuously for glusto-tests.
Ref: https://build.gluster.org/job/glusto-tests-lint/5750/console

17:59:53 Also creating executable in env/bin/python
17:59:53 Installing setuptools, pip, wheel...done.
17:59:55 Retrying (Retry(total=4, connect=None, read=None, redirect=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', error(111, 'Connection refused'))': /simple/pip/
17:59:56 Retrying (Retry(total=3, connect=None, read=None, redirect=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', error(111, 'Connection refused'))': /simple/pip/
17:59:57 Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', error(111, 'Connection refused'))': /simple/pip/
17:59:59 Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', error(111, 'Connection refused'))': /simple/pip/
18:00:03 Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', error(111, 'Connection refused'))': /simple/pip/
18:00:03 Retrying (Retry(total=4, connect=None, read=None, redirect=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', error(111, 'Connection refused'))': /simple/pip/
18:00:03 Retrying (Retry(total=3, connect=None, read=None, redirect=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', error(111, 'Connection refused'))': /simple/pip/
18:00:04 Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', error(111, 'Connection refused'))': /simple/pip/
18:00:06 Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', error(111, 'Connection refused'))': /simple/pip/
18:00:10 Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', error(111, 'Connection refused'))': /simple/pip/

**Comment by deepshikhaaa** [comment]
Rebooting the proxy server did not fix the issue. @mscherer can you please check.

**Comment by balakreddy** [comment]
We are blocked on this for pylint check for glusto-tests
@deepshikhaaa and @mscherer Any update on this?

**Comment by mscherer** [comment]
That should be fixed now.

**Comment by balakreddy** [comment]
Yes, It is fixed.
Thanks, @mscherer
