### ISSUE TITLE
Request to create a branch with name "pre_glusterfs_6_0" for glusto-tests repo master.

### ISSUE THREAD

**Issue by aloganat** [gluster/project-infrastructure#65]

**Comment by deepshikhaaa** [comment]
For glusto-tests repo, Jonathan have 'Write' manage access permissions. There's a Github's 'glusto' team with admin permissions who are actually the maintainer of glusto-tests (Akarsha and Vijay, who should also be able to provide you the access). Let me know what permissions you need here.

**Comment by aloganat** [comment]
Hi Deepshikhaaa,

All (Myself, Jonathan and Vijay) are facing this error when we try to create a branch.

[root@dhcp37-46 glusto-tests]# git push -u origin pre_glusterfs_6_0
Total 0 (delta 0), reused 0 (delta 0)
remote: Processing changes: refs: 1, done    
To ssh://aloganat@review.gluster.org/glusto-tests
 ! [remote rejected] pre_glusterfs_6_0 -> pre_glusterfs_6_0 (prohibited by Gerrit: create not permitted for refs/heads/pre_glusterfs_6_0)
error: failed to push some refs to 'ssh://aloganat@review.gluster.org/glusto-tests'

Could you help us in resolving this issue by giving permissions to create the branch.

Thanks,
Arthy

**Comment by deepshikhaaa** [comment]
Can you please check now?

**Comment by aloganat** [comment]
Still facing the same error.

[root@dhcp37-46 glusto-tests]# git push -u origin pre_glusterfs_6_0
Total 0 (delta 0), reused 0 (delta 0)
remote: Processing changes: refs: 1, done    
To ssh://aloganat@review.gluster.org/glusto-tests
 ! [remote rejected] pre_glusterfs_6_0 -> pre_glusterfs_6_0 (prohibited by Gerrit: create not permitted for refs/heads/pre_glusterfs_6_0)
error: failed to push some refs to 'ssh://aloganat@review.gluster.org/glusto-tests'

**Comment by deepshikhaaa** [comment]
Added Arthy to 'Create reference` permission on Gerrit.

It should work now.

**Comment by aloganat** [comment]
Thanks Deepshikhaaa , it works!
