### ISSUE TITLE
Smoke is failing due to smoke-centos8 job

### ISSUE THREAD

**Issue by Sheetalpamecha** [gluster/project-infrastructure#69]
This job is continuously failing for all patches https://build.gluster.org/job/smoke-centos8/-

One such case is https://review.gluster.org/#/c/glusterfs/+/24817/

**Comment by deepshikhaaa** [comment]
I have disabled the job yesterday. It should not be affecting the smoke vote now!

**Comment by Sheetalpamecha** [comment]
Thanks deepshikha, for taking care of it. we can close this issue
