### ISSUE TITLE
too many failures in devrpm-el7 job

### ISSUE THREAD

**Issue by amarts** [gluster/project-infrastructure#73]
Mostly the job fails with below error:

`20:20:58 OSError: [Errno 16] Device or resource busy: '/var/lib/mock/epel-7-x86_64/root/proc/filesystems'`

Please check

**Comment by deepshikhaaa** [comment]
It happens when the last run have some leftovers(in our case, the filesystem was not unmounted and hence was not available for another run). How about using `--orphanskill` option when we are done with the building?
It would kill off anything that is still chrooted.

**Comment by amarts** [comment]
I noticed that when there are 2 builds in parallel, this error is max. How about liimting the number of job to just 1 ? That way, only after one is complete, other can proceed, but that will reduce errors.

**Comment by deepshikhaaa** [comment]
I observed it to happen frequently failing like this because of previous run gets aborted by another patchset submission which leaves the stray processes running in the chroot. They need to be deleted/unmount before another build is triggered.

There are no 2 builds in parallel on the same machine. The build will choose another machine from the pool.

**Comment by deepshikhaaa** [comment]
Another option could be to increase this sleep time here https://github.com/gluster/build-jobs/blob/master/build-gluster-org/scripts/rpm-cleanup.sh#L5

It would be a part of rpm-cleanup step where it is taking more time to clean on el7.
Or we can simply reboot VM when the job is aborted?

**Comment by mscherer** [comment]
After discussing on irc, I agree that reboot would work, but that's, as Deepshika say, "a bit crude". 

I think the best option is indeed what Deepshika proposed:
- increase the timeout
- add some explicit mount cleanup as a backup solution.

**Comment by deepshikhaaa** [comment]
https://github.com/gluster/build-jobs/pull/38

**Comment by amarts** [comment]
Fixes looks good. No failures in last 30 jobs. :+1:
