### ISSUE TITLE
Admin access request for Gluster.org 

### ISSUE THREAD

**Issue by msaju** [gluster/project-infrastructure#76]
Please give me admin rights for Gluster.org to modify/edit the release details as well as the release timelines.

**Comment by mscherer** [comment]
@amarts  @deepshikhaaa can you confirm ?

**Comment by deepshikhaaa** [comment]
@mscherer Yes, we can give Saju the permission.

**Comment by msaju** [comment]
@mscherer - Yet to get any update.

**Comment by deepshikhaaa** [comment]
@msaju what's your username and email?

**Comment by deepshikhaaa** [comment]
I have given you admin permission.

Please check and confirm.

**Comment by msaju** [comment]
Confirmed, its working.
