### ISSUE TITLE
Need to migrate the repository rkothiya/GlusterPerformanceTestSuite to gluster

### ISSUE THREAD

**Issue by rkothiya** [gluster/project-infrastructure#78]
The following repository needs to be migrated from rkothiya/GlusterPerformanceTestSuite to gluster/gluster-performance-test-suite

Link of the repository which needs to be migrated: https://github.com/rkothiya/GlusterPerformanceTestSuite

I see that the other repositories are all in small letters with dash as the separator, I think to maintain uniformity we can do the same here.

I am ok with the change of name or any other suggestion.

**Comment by deepshikhaaa** [comment]
I think you need to pass the ownership of repo to me or Michael to get it migrate to gluster org.

**Comment by rkothiya** [comment]
I tried to transfer it to you but it says : 
Cannot find new owner 'dkhandel@redhat.com'

**Comment by rkothiya** [comment]
I tried again to transfer it to, deepshikhaaa and got the following message: 

Transfer ownership
This repository is being transferred to @deepshikhaaa.

you will need to accept the transfer, otherwise it will expire in one day.

**Comment by deepshikhaaa** [comment]
I have migrated it to Gluster.org with the changed name: https://github.com/gluster/gluster-performance-test-suite

Also, provided you the admin rights for this repo
