### ISSUE TITLE
Centos regressions are failing with error [No space left on device] 

### ISSUE THREAD

**Issue by Shwetha-Acharya** [gluster/project-infrastructure#81]
https://review.gluster.org/#/c/glusterfs/+/24896/ shows `[2020-09-16 11:23:49.122150] E [MSGID: 101012] [store.c:72:gf_store_mkstemp] 0-: Failed to open /var/lib/glusterd/vols/patchy/node_state.info.tmp. [No space left on device]` in glusterd.log

**Comment by pranithk** [comment]
Same issue is present for https://build.gluster.org/job/centos7-regression/11063/console as well.

**Comment by deepshikhaaa** [comment]
The /d is getting out of space for these new builders. We are investigating more on this and trying to figure out the new configurations for the builders on AWS. For now, I have disconnected them from Jenkins and reinstalling them again.

**Comment by mohit84** [comment]
The job is failing due to No space left on the device on the same  https://build.gluster.org/job/regression-on-demand-full-run/570/console,
