### ISSUE TITLE
Create Release 9 milestone for glusterfs project

### ISSUE THREAD

**Issue by msaju** [gluster/project-infrastructure#84]
Create new milestone - Release 9 for glusterfs.
https://github.com/gluster/glusterfs/milestones

**Comment by deepshikhaaa** [comment]
What would be the due date of this release?

**Comment by msaju** [comment]
Planned date is 11-Dec-2020.

**Comment by deepshikhaaa** [comment]
https://github.com/gluster/glusterfs/milestone/12
