### ISSUE TITLE
[bug:1787995] Move fedora smoke jobs to Fedora 31

### ISSUE THREAD

**Issue by gluster-ant** [gluster/project-infrastructure#9]
URL: https://bugzilla.redhat.com/1787995
Creator: dkhandel at redhat
Time: 20200106T05:09:33

Description of problem:

Update fedora builders to F31 for running Fedora based smoke jobs:

- devrpm-fedora

- rpm-fedora

- fedora-smoke

Warnings can be skipped for now.

**Comment by gluster-ant** [comment]
Time: 20200120T05:03:42
sankarshan.mukhopadhyay at gmail commented: 
Please change/update the bug assignee on this. And if this is being worked on (as per the conversation at the last community meeting) please change the status too.

**Comment by mscherer** [comment]
Closing, since jobs moved to a much newer fedora
