### ISSUE TITLE
./tests/00-geo-rep/00-georep-verify-non-root-setup.t failing due to mount failures

### ISSUE THREAD

**Issue by Shwetha-Acharya** [gluster/project-infrastructure#96]
In every scenario it is encountered that, mounting is failing on mount points /mnt/glusterfs/0, /mnt/glusterfs/0

07:53:49 [02:23:49] Running tests in file ./tests/00-geo-rep/00-georep-verify-non-root-setup.t
07:53:49 Timeout set is 900, default 200
08:04:14 ./tests/00-geo-rep/00-georep-verify-non-root-setup.t .. 
08:04:14 1..59
08:04:14 rm: cannot remove ‘/d/backends/patchy1/.glusterfs’: Directory not empty
08:04:14 Aborting.
08:04:14 
08:04:14 /mnt/nfs/1 could not be deleted, here are the left over items
08:04:14 drwxr-xr-x. 3 jenkins jenkins 21 Oct 18 02:23 /d/backends
08:04:14 drwxr-xr-x. 3 root root 24 Oct 18 02:22 /d/backends/patchy1
08:04:14 drw-------. 29 root root 6 Oct 18 02:22 /d/backends/patchy1/.glusterfs

08:04:14 not ok  46 [     16/  50169] < 256> '^1$ check_mounted /mnt/glusterfs/0' -> 'Got "0" instead of "^1$"'
08:04:14 not ok  47 [     10/  50121] < 257> '^1$ check_mounted /mnt/glusterfs/1' -> 'Got "0" instead of "^1$"'

This issue was not reproducible. Please verify this issue issue on build machines.
Some recommened tests:
$ mount -t glusterfs <ip>:<volname> /mnt/glusterfs/0
$ df -kh /mnt/glusterfs/0
$ umount /mnt/glusterfs/0

https://build.gluster.org/job/gh_centos7-regression/135/consoleFull

**Comment by deepshikhaaa** [comment]
It was mainly failing on 206 builder. I did disconnect it from the pool and found out `/d/backends` is not removing a hidden folder even after manually removing it. Misc found out a corrupted FS and fixed it by `xfs repair /var/data` after unmounting /d. The test seems to be passing now. 

Please reopen if it fails again.
