### ISSUE TITLE
Not able to run regression

### ISSUE THREAD

**Issue by schaffung** [gluster/project-infrastructure#97]
I believe that everyone should be able to trigger regressions in the Glusterfs project as it can be sort of annoying to bug the maintainers again and again for running the regressions.

**Comment by mscherer** [comment]
I always tought the policy was in place to avoid random people to run code on our builders without verification. Granted, this could be achieve already with a patch in configure/makefile to run code at compile time.

@amarts any opinion ?

**Comment by deepshikhaaa** [comment]
We had a discussion on gchat and one suggestion from Raghavendra is:

Common solution(Used by OpenShift/Kubernetes/Heketi): 
1. Don't run regression if the PR owner is not known to us(Github/CI system)
2. Run regression if the PR owner is in the contributor list. Openshift/Kubernetes run the test for anyone who is part of the Org in Github. In heketi, we maintain a list https://github.com/gluster/centosci/blob/master/jobs/heketi-functional.yml#L37. So both the approaches require manual intervention for a new contributor, one is UI based and the other requires a PR in the centosci repo.

It seems to be doable if everyone is in favor and want to not limit the regression to maintainers only.

**Comment by mscherer** [comment]
So what is "know by us" ?

And also, if we use the "part of the org", we should also have a process to be part of the org. I have asked for that since years and so far, no one had a criteria.

**Comment by schaffung** [comment]
@mscherer , valid point, I actually don't see any criteria as to how to be part of the org. I feel we should have one as part of our guidelines, with this current issue in hand maybe it is high time we get one...

**Comment by deepshikhaaa** [comment]
https://docs.google.com/document/d/1Vxf24dLPSCmVBfJ7PfO5bN28r9slfyoJufZX2GOzlTc/edit?usp=sharing doc on criteria to be a member of gluster org. It is still under review though.

**Comment by schaffung** [comment]
@deepshikhaaa , the above doc can be used as a guideline for managing the org. But with regards to the existing contributors who are part of the gluster org can they be provided the permission to run the regression tests? The reason being currently we have to drop a message to all maintainers requesting for regression and the dev work is delayed due to that. Merging I can understand that it is under the purview of the maintainers but maybe regression invocation can be done my all members of the org.

Once the guideline is reviewed and enforced, maybe then certain new members will be added and inactive member's permission will be revoked.

**Comment by schaffung** [comment]
@gluster/gluster-maintainers and @gluster/glusterfs-dev  ^^ can this be taken to resolution because it is sort of annoying to ask the maintainers to run regressions every now and then. And even from a dev perspective, it might hinder your flow while working to be constantly pinged wherein some contributor is requesting you to run a regression command.

**Comment by deepshikhaaa** [comment]
@srijan-sivakumar I have made the changes in the configs last week. Gluster org members should be able to run the regression on the PRs.

Let me know if it is working for you.

**Comment by schaffung** [comment]
@deepshikhaaa , yes I'm able to trigger regression now. Thank you. I think the issue can be closed..
