### ISSUE TITLE
Update Community meeting link in Gluster-users email signature.

### ISSUE THREAD

**Issue by msaju** [gluster/project-infrastructure#99]
Have updated the community meeting link to  - meet.google.com/cpu-eiue-hvk
Need to update the above link to the Gluster-users email signature.

**Comment by mscherer** [comment]
Can you give me the text, you want ? (like, just the url )

Or would you prefer to be added as a admin on the list (mostly moderation job, so pretty borring)

**Comment by msaju** [comment]
The meeting link is as below.
https://meet.google.com/cpu-eiue-hvk

**Comment by mscherer** [comment]
Right now, we have:
```
Participate in our active IRC channel at #gluster on irc.freenode.net for more information, or look for more information at https://www.gluster.org/ 
```
Do you want to place the link at the end, at the start, replace the whole signature ? No other text (like the date/time) ?

**Comment by msaju** [comment]
What I am seeing is the below attached signature in gluster-user mailing list.
![image](https://user-images.githubusercontent.com/63098029/97891338-abb29d00-1d54-11eb-8f04-2e4a26bec7cd.png)

Would like to change the Bridge link with the link shared above.

**Comment by mscherer** [comment]
Ok, indeed I was looking at the wrong setting, that was the message for new subscriber, not the sig (which is not in "general", but non digest options"...), it make a lot more sense.

I fixed it, tell me if that's that's rendering correctly

**Comment by msaju** [comment]
Its coming properly, you can close this.
